### ISSUE TITLE
Missing files

### ISSUE THREAD

**Issue by dth2** [jeffrlin/tractxwalk#1]
Hi,
I have some questions about missing files for this repo. The read.ME.pdf refers to several folder including the code/ data/ and results/ folders that should contain the stata code and data for reproducing your research. Unfortunately those folders don't seem to be included in the repo.  Some colleagues and I are very interested in using your methods for cross-walking census tracks from 1940 to 2010. Can you direct me to the code and data that was used.

Thanks
Deven

**Comment by jeffrlin** [comment]
Those data should be available in the replication package, available at the journal's repo. 

Visit here: https://doi.org/10.1093/restud/rdx018
and scroll down to "Supplemental data": https://academic.oup.com/restud/article/85/1/663/3091867#106838793
