### ISSUE TITLE
Area weights out of range

### ISSUE THREAD

**Issue by dth2** [jeffrlin/tractxwalk#2]
Hi,
I am trying to apply the area weights from the 1960s to 2010 crosswalk and the results are somewhat confusing. There are many weights over 100 and some even over 1000 so that when, for example, the total population in a 1960 gisjoin is multiplied by the weight to get the proportion of the 1960 population in the the 2010 gisjoin the population size in increased by a magnitude of 100 or even a thousand.  The result in that, for example, the population in the 2010 gisjoin2010 G0600710010409 in Riverside California is predicted to have a population of 55,683,497 in 1960. Clearly this is not possible. Perhaps I am not interpreting the area weights correctly but I don't think there should be any values much larger than 1. Any clarity would be appreciated.

**Comment by jeffrlin** [comment]
Sorry for the delayed reply.

No, the area weights are in units of land area, so there is no requirement that they be less than or equal to 1. To obtain the share of the total 2010 tract area, sum the area weights *within* gisjoin2010.
